---
name: Publish to Anaconda

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  publish:
    name: Build and publish to Anaconda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Publish to Anaconda
        uses: fcakyon/conda-publish-action@v1.3
        with:
          subdir: 'conda'
          anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
          platforms: 'noarch'
...
